# Generated by Django 5.0.8 on 2024-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisits',
            name='path',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
